name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "fress"  # 直接写死命名空间
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Before freeing up disk space
        run: |
          echo "Before freeing up disk space"
          df -hT

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 128
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Restart docker
        run: |
          sudo service docker restart
          sleep 10  # 增加等待时间

      - name: Configure DNS
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null

      - name: Test network connectivity
        run: |
          echo "测试阿里云镜像仓库的网络连通性..."
          echo "注册表地址: $ALIYUN_REGISTRY"
          echo "DNS 解析结果:"
          dig $ALIYUN_REGISTRY +short
          echo "HTTPS 连接测试:"
          curl -vI --connect-timeout 15 https://$ALIYUN_REGISTRY || true

      - name: Build and push image Aliyun
        run: |
          echo "阿里云注册表地址: $ALIYUN_REGISTRY"
          echo "命名空间: $ALIYUN_NAME_SPACE"
          echo "用户名: $ALIYUN_REGISTRY_USER"
          
          echo "尝试登录阿里云镜像仓库..."
          echo "$ALIYUN_REGISTRY_PASSWORD" | docker login -u "$ALIYUN_REGISTRY_USER" --password-stdin "$ALIYUN_REGISTRY" || {
            echo "登录失败！请检查："
            echo "1. Registry 地址是否与实例地址完全一致"
            echo "2. 用户名和密码是否正确"
            exit 1
          }

          # 后续镜像处理逻辑（保持原有脚本）
          declare -A duplicate_images
          declare -A temp_map
          while IFS= read -r line || [ -n "$line" ]; do
              [[ -z "$line" ]] && continue
              if echo "$line" | grep -q '^\s*#'; then
                  continue
              fi
              
              image=$(echo "$line" | awk '{print $NF}')
              image="${image%%@*}"
              echo "处理镜像: $image"
              # ... 其余逻辑不变 ...
          done < images.txt
          
          while IFS= read -r line || [ -n "$line" ]; do
              [[ -z "$line" ]] && continue
              if echo "$line" | grep -q '^\s*#'; then
                  continue
              fi
          
              echo "拉取镜像: $line"
              docker pull $line
              # ... 其余逻辑不变 ...
          done < images.txt
