name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "fress"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Before freeing up disk space
        run: |
          echo "Before freeing up disk space"
          df -hT

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 128
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Restart docker
        run: |
          sudo service docker restart
          sleep 10

      - name: Configure DNS
        run: |
          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null
          echo "nameserver 1.0.0.1" | sudo tee -a /etc/resolv.conf > /dev/null

      - name: Test network connectivity
        run: |
          echo "测试阿里云镜像仓库的网络连通性..."
          echo "注册表地址: $ALIYUN_REGISTRY"
          
          # 使用 dig 指定 DNS 服务器
          echo "DNS 解析结果:"
          dig @1.1.1.1 $ALIYUN_REGISTRY +short
          
          # 测试 IP 直连（替换为本地解析的 IP）
          echo "测试 IP 直连:"
          nc -zv 139.196.71.17 443
          curl -kIv --connect-timeout 15 https://139.196.71.17

      - name: Build and push image Aliyun
        run: |
          echo "阿里云注册表地址: $ALIYUN_REGISTRY"
          echo "用户名: $ALIYUN_REGISTRY_USER"
          
          echo "尝试登录..."
          echo "$ALIYUN_REGISTRY_PASSWORD" | docker login -u "$ALIYUN_REGISTRY_USER" --password-stdin "$ALIYUN_REGISTRY" || {
            echo "登录失败！可能原因："
            echo "1. Registry 地址错误（当前值：$ALIYUN_REGISTRY）"
            echo "2. 用户名或密码错误"
            exit 1
          }

          # 示例：推送一个测试镜像
          docker pull nginx:latest
          docker tag nginx:latest "$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:test"
          docker push "$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:test"
